version: '2'
services:
    conference-app:
        image: conference
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://conference-mysql:3306/conference?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    conference-mysql:
        extends:
            file: mysql.yml
            service: conference-mysql
